services:
  rsa_dev:
    image: rsa_project
    build: .
    container_name: rsa_dev
    ports:
      - "3000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://rsa_user:rsa_password@db:5432/rsa_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: rsa_db
    environment:
      POSTGRES_USER: rsa_user
      POSTGRES_PASSWORD: rsa_password
      POSTGRES_DB: rsa_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rsa_user -d rsa_db"]
      interval: 5s
      timeout: 5s
      retries: 5
